// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxevjwqbruzegksgxttb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4ZXZqd3FicnV6ZWdrc2d4dHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjkxNzcsImV4cCI6MjA2NzE0NTE3N30.L8MmcSJ33FLs0vJEjdvpNvpG3cUi8rmOzoZJPFIAIE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});